# Generated by Django 3.1.8 on 2021-04-09 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Citizenprofile',
        ),
    ]
