# Generated by Django 3.1.8 on 2021-04-13 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_citizenprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='FIR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_Of_crime', models.TextField()),
                ('date_and_time', models.DateTimeField()),
                ('description_of_crime', models.TextField()),
                ('FIR_againts', models.TextField()),
                ('Proof', models.FileField(upload_to='proof')),
                ('status', models.CharField(max_length=20)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.citizenprofile')),
            ],
        ),
    ]
