# Generated by Django 3.1.8 on 2021-04-14 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_fir'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FIR',
        ),
    ]
