# Generated by Django 3.1.8 on 2021-04-14 09:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_delete_fir'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fir',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_place', models.TextField()),
                ('Date_and_Time', models.DateTimeField()),
                ('Crime_Description', models.TextField()),
                ('Fir_againts', models.TextField()),
                ('proof', models.FileField(upload_to='proof')),
                ('status', models.CharField(choices=[('Activate', 'Activate'), ('Inprocess', 'Inprocess'), ('Closed', 'Closed')], max_length=20)),
                ('Reason', models.CharField(max_length=256)),
                ('FIR_Date_and_Time', models.DateTimeField(default=django.utils.timezone.now)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.citizenprofile')),
            ],
        ),
    ]
