# Generated by Django 3.1.7 on 2021-04-14 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_auto_20210415_0030'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_place', models.TextField()),
                ('Date_and_Time', models.DateTimeField()),
                ('Crime_Description', models.TextField()),
                ('complain_againts', models.TextField()),
                ('proof', models.FileField(null=True, upload_to='proof')),
                ('status', models.CharField(choices=[('Activate', 'Activate'), ('Inprocess', 'Inprocess'), ('Closed', 'Closed')], max_length=20)),
                ('Reason', models.CharField(max_length=256)),
                ('complain_Date_and_Time', models.DateTimeField(blank=True, null=True)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.citizenprofile')),
            ],
        ),
    ]
