# Generated by Django 3.1.8 on 2021-04-15 07:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_auto_20210415_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complain',
            name='complain_Date_and_Time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='fir',
            name='FIR_Date_and_Time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
