# Generated by Django 3.1.8 on 2021-04-16 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_auto_20210415_1322'),
    ]

    operations = [
        migrations.CreateModel(
            name='Police_Station',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('st_name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('phone_no', models.CharField(max_length=200)),
            ],
        ),
    ]
