# Generated by Django 3.1.8 on 2021-04-16 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_police_station'),
    ]

    operations = [
        migrations.RenameField(
            model_name='police_station',
            old_name='st_name',
            new_name='Police_station_name',
        ),
    ]
