# Generated by Django 3.1.8 on 2021-04-16 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_auto_20210416_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='police_station',
            name='address',
            field=models.TextField(max_length=200),
        ),
    ]
