# Generated by Django 3.1.8 on 2021-04-17 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_photos_videos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photos_videos',
            name='Description',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='photos_videos',
            name='Photo',
            field=models.ImageField(max_length=500, upload_to='photos_videos/'),
        ),
        migrations.AlterField(
            model_name='photos_videos',
            name='Video',
            field=models.FileField(max_length=500, upload_to='photos_videos/'),
        ),
    ]
