# Generated by Django 3.2 on 2021-04-26 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_crime_sub_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='fir',
            name='crime_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.crime_category'),
        ),
    ]
