# Generated by Django 3.2 on 2021-04-26 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0026_fir_crime_sub_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crime_sub_category',
            old_name='Crime_Category',
            new_name='crime_category',
        ),
    ]
