# Generated by Django 3.2 on 2021-04-27 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0027_rename_crime_category_crime_sub_category_crime_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='fir',
            name='police_station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.police_station'),
        ),
    ]
