# Generated by Django 3.2 on 2021-04-29 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0033_village'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area_Police_Station',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.city')),
                ('inspector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.inspector')),
                ('police_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.police_station')),
                ('taluka', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.taluka')),
                ('village', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.village')),
            ],
        ),
    ]
