# Generated by Django 3.2 on 2021-04-30 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0034_area_police_station'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Area_Police_Station',
        ),
    ]
