# Generated by Django 3.2 on 2021-04-30 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0035_delete_area_police_station'),
    ]

    operations = [
        migrations.AddField(
            model_name='police_station',
            name='Village',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.village'),
        ),
        migrations.AddField(
            model_name='police_station',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.city'),
        ),
        migrations.AddField(
            model_name='police_station',
            name='email_address',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='police_station',
            name='mobile_no',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='police_station',
            name='taluka',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.taluka'),
        ),
        migrations.AlterField(
            model_name='police_station',
            name='phone_no',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
