# Generated by Django 3.2 on 2021-04-30 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0036_auto_20210430_1149'),
    ]

    operations = [
        migrations.RenameField(
            model_name='police_station',
            old_name='Village',
            new_name='village',
        ),
    ]
