# Generated by Django 3.2 on 2021-05-01 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0037_rename_village_police_station_village'),
    ]

    operations = [
        migrations.AddField(
            model_name='fir',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.village'),
        ),
    ]
