# Generated by Django 3.2 on 2021-05-01 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0038_fir_area'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fir',
            name='area',
        ),
    ]
