# Generated by Django 3.2 on 2021-05-03 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0039_remove_fir_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='fir',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.city'),
        ),
        migrations.AddField(
            model_name='fir',
            name='taluka',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.taluka'),
        ),
        migrations.AddField(
            model_name='fir',
            name='village',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.village'),
        ),
    ]
