# Generated by Django 3.2 on 2021-05-05 19:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0041_auto_20210503_1658'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.CharField(choices=[('INP', 'Inspector'), ('SINP', 'Sub-Inspector'), ('CNST', 'Constable'), ('CMSNR', 'Commissioner')], max_length=256)),
                ('Salary', models.DecimalField(decimal_places=2, max_digits=7)),
                ('profile_pic', models.ImageField(upload_to='profile_pic')),
                ('Age', models.IntegerField()),
                ('date_of_birth', models.DateField()),
                ('mobile_no', models.IntegerField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
                ('pincode', models.IntegerField()),
                ('police_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.police_station')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Inspector',
        ),
    ]
