# Generated by Django 3.2 on 2021-05-06 16:04

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0045_remove_profiles_salary'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profiles',
            new_name='Inspector',
        ),
    ]
