# Generated by Django 3.2 on 2021-05-06 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0046_rename_profiles_inspector'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inspector_login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=256)),
                ('first_name', models.CharField(max_length=256)),
                ('last_name', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Service_Officers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('constable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.constable')),
                ('inspector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.inspector_login')),
                ('police_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.police_station')),
                ('sub_inspector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.sub_inspector')),
            ],
        ),
    ]
