# Generated by Django 3.2 on 2021-05-07 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0051_inspector_police_station'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inspector',
            name='police_station',
        ),
        migrations.DeleteModel(
            name='Service_Officers',
        ),
    ]
