# Generated by Django 3.2 on 2021-05-07 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0052_auto_20210507_2100'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service_Officers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('constable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.constable')),
                ('inspector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.inspector_login')),
                ('police_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.police_station')),
                ('sub_inspector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.sub_inspector')),
            ],
        ),
    ]
