# Generated by Django 3.2 on 2021-05-07 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0054_inspector_police_station'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspector',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.inspector_login', unique=True),
        ),
    ]
