# Generated by Django 3.2 on 2021-05-08 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0056_auto_20210508_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complain',
            name='proof',
            field=models.FileField(blank=True, null=True, upload_to='proof'),
        ),
        migrations.AlterField(
            model_name='fir',
            name='proof',
            field=models.FileField(blank=True, null=True, upload_to='proof'),
        ),
    ]
