# Generated by Django 3.2 on 2021-05-12 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0058_alter_complain_date_and_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='Photo',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='photos_videos/'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='Video',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='photos_videos/'),
        ),
        migrations.DeleteModel(
            name='Photos_Videos',
        ),
    ]
