# Generated by Django 3.2 on 2021-05-13 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0059_auto_20210512_2257'),
    ]

    operations = [
        migrations.CreateModel(
            name='Messing_Persons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Full_Name', models.CharField(max_length=256)),
                ('Photo', models.ImageField(upload_to='missing_persons')),
                ('Date_of_birth', models.DateField()),
                ('Age', models.IntegerField()),
                ('Nickname', models.CharField(blank=True, max_length=256, null=True)),
                ('weight', models.IntegerField()),
                ('height', models.IntegerField()),
                ('Skin_color', models.CharField(max_length=256)),
                ('Missing_Date', models.DateField()),
                ('Address', models.TextField()),
                ('Contact_no', models.IntegerField()),
            ],
        ),
    ]
