# Generated by Django 3.2 on 2021-05-13 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0061_alter_messing_persons_height'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messing_persons',
            name='Contact_no',
            field=models.BigIntegerField(),
        ),
    ]
