# Generated by Django 3.2 on 2021-05-13 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0062_alter_messing_persons_contact_no'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Messing_Persons',
            new_name='Missing_Persons',
        ),
    ]
