# Generated by Django 3.2 on 2021-05-13 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0063_rename_messing_persons_missing_persons'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rules_Regulations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=256)),
                ('Document', models.FileField(upload_to='rules_regulation')),
            ],
        ),
    ]
