# Generated by Django 3.2 on 2021-05-14 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0065_commissioner_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service_officers',
            name='constable',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myapp.constable'),
        ),
        migrations.AlterField(
            model_name='service_officers',
            name='inspector',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myapp.inspector_login'),
        ),
        migrations.AlterField(
            model_name='service_officers',
            name='police_station',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myapp.police_station'),
        ),
        migrations.AlterField(
            model_name='service_officers',
            name='sub_inspector',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myapp.sub_inspector'),
        ),
    ]
