# Generated by Django 3.2 on 2021-05-14 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0069_alter_constable_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constable',
            name='username',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
