# Generated by Django 3.2 on 2021-05-15 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0071_commissioner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emergency_Information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Number', models.BigIntegerField()),
            ],
        ),
    ]
